# Generated by Django 4.1.6 on 2023-02-08 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('944d5b90-658a-42dc-9c6b-9524dc3c6f12'), editable=False, primary_key=True, serialize=False),
        ),
    ]
