# Generated by Django 4.1.6 on 2023-02-08 08:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_basemodel_created_at_alter_basemodel_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('67b34f95-a78c-11ed-9fb8-ecf4bb3acd17'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time', to='home.time'),
        ),
    ]
